// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFZHD46yE9Lh-DlRxHS5ma8Y3oHARZFq0',
    appId: '1:795844478666:web:2cecfb47684f6adf66d633',
    messagingSenderId: '795844478666',
    projectId: 'testproject-8941c',
    authDomain: 'testproject-8941c.firebaseapp.com',
    databaseURL: 'https://testproject-8941c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testproject-8941c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD08BvTBbX20GZyKX4LNuddVZ7XduppKzE',
    appId: '1:795844478666:android:502a79ce4b2f66dc66d633',
    messagingSenderId: '795844478666',
    projectId: 'testproject-8941c',
    databaseURL: 'https://testproject-8941c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testproject-8941c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi64todUq9EMIJWsCk-47Dkro1DpaBomU',
    appId: '1:795844478666:ios:15576bef3da6dc7766d633',
    messagingSenderId: '795844478666',
    projectId: 'testproject-8941c',
    databaseURL: 'https://testproject-8941c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testproject-8941c.appspot.com',
    iosClientId: '795844478666-oa42v2uqje3pu4q8aeto18lj5qpsl0p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.testWeb',
  );
}
